# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/externaldns.k8s.io/dnsendpoint_v1alpha1.json
---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: cloudflared-tunnel
spec:
  endpoints:
    - dnsName: external.grappleberry.xyz
      recordTTL: 1
      recordType: CNAME
      targets:
        - 6e5ac84c-22c7-4a51-891e-1a5133ab9e54.cfargotunnel.com
