# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflared
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: cloudflared-secret
    template:
      data:
        credentials.json: "{{ .TUNNEL_CREDENTIALS }}"
        config.yaml: |
          tunnel: {{ .TUNNEL_ID }}
          credentials-file: /etc/cloudflared/creds/credentials.json
          metrics: 0.0.0.0:8080
          no-autoupdate: true
          ingress:
            - hostname: overseerr.grappleberry.xyz
              originRequest:
                http2Origin: true
                originServerName: overseerr.grappleberry.xyz
              service: https://router-grappleberry.openshift-ingress.svc.cluster.local:443
            - service: http_status:404
  dataFrom:
    - extract:
        key: cloudflare
