# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/security.openshift.io/securitycontextconstraints_v1.json
---
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: volsync-nfs-mover
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: false
allowPrivilegedContainer: false
allowedCapabilities: null
defaultAddCapabilities: null
fsGroup:
  type: RunAsAny
readOnlyRootFilesystem: true
requiredDropCapabilities:
  - ALL
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
users: []
groups: []
volumes:
  - configMap
  - downwardAPI
  - emptyDir
  - nfs
  - persistentVolumeClaim
  - projected
  - secret
