# yaml-language-server: $schema=https://json.schemastore.org/kustomization
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # No namespace.yaml - kube-system is pre-created by Kubernetes
  - ./kube-vip/ks.yaml
  - ./reloader/ks.yaml
