# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gluetun
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: gluetun-secret
    template:
      data:
        WIREGUARD_PRIVATE_KEY: "{{ .wireguard_private_key }}"
  dataFrom:
    - extract:
        key: gluetun
