# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: qbittorrent
  values:
    controllers:
      qbittorrent:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-dirs:
            image:
              repository: docker.io/library/busybox
              tag: 1.37.0
            command:
              - sh
              - -c
              - mkdir -p /downloads/torrents/complete /downloads/torrents/incomplete
            securityContext:
              runAsUser: 1000
              runAsGroup: 1000
              runAsNonRoot: true
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop: ["ALL"]
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/qbittorrent
              tag: 5.1.4
            env:
              TZ: Asia/Dubai
              QBT_WEBUI_PORT: "8080"
              QBT_TORRENTING_PORT: "6881"
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/v2/app/version
                    port: 8080
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/v2/app/version
                    port: 8080
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop: ["ALL"]
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                cpu: 1000m
                memory: 4Gi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seLinuxOptions:
          level: "s0"
    service:
      app:
        controller: qbittorrent
        ports:
          http:
            port: 8080
      bittorrent:
        controller: qbittorrent
        type: LoadBalancer
        ports:
          bittorrent-tcp:
            port: 6881
            protocol: TCP
          bittorrent-udp:
            port: 6881
            protocol: UDP
    persistence:
      config:
        existingClaim: qbittorrent-config
      downloads:
        existingClaim: downloads
        globalMounts:
          - path: /downloads
      media:
        type: nfs
        server: nas.grappleberry.xyz
        path: /volume1/media
        globalMounts:
          - path: /media
      tmp:
        type: emptyDir
