---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: qbittorrent
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: qbittorrent-gluetun-scc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:qbittorrent-gluetun
subjects:
  - kind: ServiceAccount
    name: qbittorrent
