# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prowlarr
spec:
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: prowlarr
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    controllers:
      prowlarr:
        annotations:
          reloader.stakater.com/auto: "true"
        serviceAccount:
          name: prowlarr
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/prowlarr
              tag: 2.5.0.5422
            env:
              PROWLARR__SERVER__PORT: "9696"
              TZ: Asia/Dubai
              DOTNET_SYSTEM_NET_DISABLEIPV6: "true"
            envFrom:
              - secretRef:
                  name: prowlarr-secret
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: 9696
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: 9696
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: 9696
                  periodSeconds: 10
                  failureThreshold: 30
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop: ["ALL"]
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                cpu: 500m
                memory: 1Gi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seLinuxOptions:
          level: "s0"
    service:
      app:
        controller: prowlarr
        ports:
          http:
            port: 9696
    persistence:
      config:
        existingClaim: prowlarr-config
      tmp:
        type: emptyDir
