# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/route.openshift.io/route_v1.json
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: bazarr
  labels:
    ingress: grappleberry
spec:
  host: bazarr.grappleberry.xyz
  port:
    targetPort: 6767
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  to:
    kind: Service
    name: bazarr
    weight: 100
  wildcardPolicy: None
