---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: csi-sidecar-role
rules:
  - apiGroups: [""]
    resources: [persistentvolumes]
    verbs: [get, list, watch, update, patch]
  - apiGroups: [""]
    resources: [nodes]
    verbs: [get, list, watch]
  - apiGroups: [""]
    resources: [secrets]
    verbs: [get, list, watch]
  - apiGroups: [""]
    resources: [events]
    verbs: [list, watch, create, update, patch]
  - apiGroups: [""]
    resources: [pods]
    verbs: [get, list, watch]
  - apiGroups: [""]
    resources: [persistentvolumeclaims]
    verbs: [get, list, watch, update]
  - apiGroups: [""]
    resources: [persistentvolumeclaims/status]
    verbs: [update, patch]
  - apiGroups: [storage.k8s.io]
    resources: [volumeattachments]
    verbs: [get, list, watch, update, patch]
  - apiGroups: [storage.k8s.io]
    resources: [volumeattachments/status]
    verbs: [patch]
  - apiGroups: [storage.k8s.io]
    resources: [csinodes]
    verbs: [get, list, watch]
  - apiGroups: [storage.k8s.io]
    resources: [storageclasses]
    verbs: [get, list, watch]
  - apiGroups: [storage.k8s.io]
    resources: [volumesnapshotclasses, volumesnapshotcontents, volumesnapshots]
    verbs: [get, list, watch, update, patch, create, delete]
  - apiGroups: [snapshot.storage.k8s.io]
    resources: [volumesnapshotclasses, volumesnapshotcontents, volumesnapshots]
    verbs: [get, list, watch, update, patch, create, delete]
  - apiGroups: [snapshot.storage.k8s.io]
    resources: [volumesnapshotcontents/status, volumesnapshots/status]
    verbs: [update, patch]
  - apiGroups: [coordination.k8s.io]
    resources: [leases]
    verbs: [get, watch, list, delete, update, create]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rbd-ctrlplugin-sa
  namespace: rook-ceph
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cephfs-ctrlplugin-sa
  namespace: rook-ceph
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rbd-nodeplugin-sa
  namespace: rook-ceph
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cephfs-nodeplugin-sa
  namespace: rook-ceph
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rbd-ctrlplugin-sa-csi-sidecar
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: csi-sidecar-role
subjects:
  - kind: ServiceAccount
    name: rbd-ctrlplugin-sa
    namespace: rook-ceph
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cephfs-ctrlplugin-sa-csi-sidecar
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: csi-sidecar-role
subjects:
  - kind: ServiceAccount
    name: cephfs-ctrlplugin-sa
    namespace: rook-ceph
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rbd-nodeplugin-sa-csi-sidecar
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: csi-sidecar-role
subjects:
  - kind: ServiceAccount
    name: rbd-nodeplugin-sa
    namespace: rook-ceph
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cephfs-nodeplugin-sa-csi-sidecar
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: csi-sidecar-role
subjects:
  - kind: ServiceAccount
    name: cephfs-nodeplugin-sa
    namespace: rook-ceph
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rbd-ctrlplugin-sa-scc-rook-ceph-csi
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:rook-ceph-csi
subjects:
  - kind: ServiceAccount
    name: rbd-ctrlplugin-sa
    namespace: rook-ceph
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cephfs-ctrlplugin-sa-scc-rook-ceph-csi
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:rook-ceph-csi
subjects:
  - kind: ServiceAccount
    name: cephfs-ctrlplugin-sa
    namespace: rook-ceph
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rbd-nodeplugin-sa-scc-rook-ceph-csi
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:rook-ceph-csi
subjects:
  - kind: ServiceAccount
    name: rbd-nodeplugin-sa
    namespace: rook-ceph
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cephfs-nodeplugin-sa-scc-rook-ceph-csi
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:rook-ceph-csi
subjects:
  - kind: ServiceAccount
    name: cephfs-nodeplugin-sa
    namespace: rook-ceph
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: csi-sidecar-leader-election
  namespace: rook-ceph
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ceph-csi-leader-election-role
subjects:
  - kind: ServiceAccount
    name: rbd-ctrlplugin-sa
    namespace: rook-ceph
  - kind: ServiceAccount
    name: cephfs-ctrlplugin-sa
    namespace: rook-ceph
  - kind: ServiceAccount
    name: rbd-nodeplugin-sa
    namespace: rook-ceph
  - kind: ServiceAccount
    name: cephfs-nodeplugin-sa
    namespace: rook-ceph
