# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/configmap.json
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
data:
  config.yaml: |-
    enableUserWorkload: true
    prometheusK8s:
      retention: 15d
      volumeClaimTemplate:
        spec:
          storageClassName: ceph-block
          resources:
            requests:
              storage: 50Gi
    alertmanagerMain:
      volumeClaimTemplate:
        spec:
          storageClassName: ceph-block
          resources:
            requests:
              storage: 10Gi
