# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/configmap.json
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
data:
  config.yaml: |-
    enableUserWorkload: true
    prometheusK8s:
      retention: 15d
      nodeSelector:
        node-role.kubernetes.io/worker: ""
      volumeClaimTemplate:
        spec:
          storageClassName: ceph-block
          resources:
            requests:
              storage: 50Gi
    alertmanagerMain:
      nodeSelector:
        node-role.kubernetes.io/worker: ""
      volumeClaimTemplate:
        spec:
          storageClassName: ceph-block
          resources:
            requests:
              storage: 10Gi
    prometheusOperator:
      nodeSelector:
        node-role.kubernetes.io/worker: ""
    kubeStateMetrics:
      nodeSelector:
        node-role.kubernetes.io/worker: ""
    openshiftStateMetrics:
      nodeSelector:
        node-role.kubernetes.io/worker: ""
    telemeterClient:
      nodeSelector:
        node-role.kubernetes.io/worker: ""
    thanosQuerier:
      nodeSelector:
        node-role.kubernetes.io/worker: ""
    monitoringPlugin:
      nodeSelector:
        node-role.kubernetes.io/worker: ""
    metricsServer:
      nodeSelector:
        node-role.kubernetes.io/worker: ""
