# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/scheduling.k8s.io/priorityclass_v1.json
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: infrastructure-critical
value: 1000000
globalDefault: false
description: Priority class for critical infrastructure components
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: storage-critical
value: 900000
globalDefault: false
description: Priority class for storage components (Rook-Ceph)
