# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/grafana.integreatly.org/grafanafolder_v1beta1.json
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  name: kubernetes
spec:
  uid: kubernetes
  instanceSelector:
    matchLabels:
      grafana.internal/instance: grafana
  title: Kubernetes
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  name: infrastructure
spec:
  uid: infrastructure
  instanceSelector:
    matchLabels:
      grafana.internal/instance: grafana
  title: Infrastructure
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  name: observability
spec:
  uid: observability
  instanceSelector:
    matchLabels:
      grafana.internal/instance: grafana
  title: Observability
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  name: flux
spec:
  uid: flux
  instanceSelector:
    matchLabels:
      grafana.internal/instance: grafana
  title: Flux
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  name: security
spec:
  uid: security
  instanceSelector:
    matchLabels:
      grafana.internal/instance: grafana
  title: Security
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  name: storage
spec:
  uid: storage
  instanceSelector:
    matchLabels:
      grafana.internal/instance: grafana
  title: Storage
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  name: logging
spec:
  uid: logging
  instanceSelector:
    matchLabels:
      grafana.internal/instance: grafana
  title: Logging
