# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-issuers-config
  namespace: flux-system
spec:
  targetNamespace: cert-manager
  path: ./kubernetes/infrastructure/configs/cluster-issuers-config/app
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: cert-manager
      namespace: flux-system
    - name: cluster-secrets
      namespace: flux-system
  healthChecks:
    - apiVersion: cert-manager.io/v1
      kind: ClusterIssuer
      name: letsencrypt-production
      namespace: cert-manager
  interval: 10m
  timeout: 5m
  retryInterval: 2m
  prune: true
  wait: true
