# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/machineconfiguration.openshift.io/machineconfig_v1.json
---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: 99-master-load-ipvs-modules
  labels:
    machineconfiguration.openshift.io/role: master
spec:
  config:
    ignition:
      version: 3.2.0
    storage:
      files:
        - path: /etc/modules-load.d/ipvs.conf
          mode: 0644
          overwrite: true
          contents:
            source: data:text/plain;charset=utf-8,ip_vs%0Aip_vs_rr%0Aip_vs_wrr%0Aip_vs_sh%0Anf_conntrack
