# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: onepassword-connect
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: onepassword-connect
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    connect:
      serviceType: ClusterIP
      api:
        imageRepository: docker.io/1password/connect-api
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
          limits:
            memory: 128Mi
      sync:
        imageRepository: docker.io/1password/connect-sync
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
          limits:
            memory: 128Mi
  valuesFrom:
    - kind: Secret
      name: onepassword-connect-credentials
      valuesKey: credentials_base64
      targetPath: connect.credentials_base64
