# yaml-language-server: $schema=https://json.schemastore.org/kustomization
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # No namespace.yaml - openshift-monitoring is pre-created by OKD
  - ./cluster-monitoring-config/ks.yaml
  - ./user-workload-config/ks.yaml
