---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: devopsarr
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: devopsarr-secrets
    template:
      data:
        prowlarr_api_key: "{{ .prowlarr_api_key }}"
        sonarr_api_key: "{{ .sonarr_api_key }}"
        radarr_api_key: "{{ .radarr_api_key }}"
        sabnzbd_api_key: "{{ .sabnzbd_api_key }}"
        nzbgeek_api_key: "{{ .nzbgeek_api_key }}"
        qbittorrent_username: "{{ .qbittorrent_username }}"
        qbittorrent_password: "{{ .qbittorrent_password }}"
        plex_token: "{{ .plex_token }}"
  data:
    - secretKey: prowlarr_api_key
      remoteRef:
        key: prowlarr
        property: api_key
    - secretKey: sonarr_api_key
      remoteRef:
        key: sonarr
        property: api_key
    - secretKey: radarr_api_key
      remoteRef:
        key: radarr
        property: api_key
    - secretKey: sabnzbd_api_key
      remoteRef:
        key: sabnzbd
        property: api_key
    - secretKey: nzbgeek_api_key
      remoteRef:
        key: nzbgeek
        property: api_key
    - secretKey: qbittorrent_username
      remoteRef:
        key: qbittorrent
        property: username
    - secretKey: qbittorrent_password
      remoteRef:
        key: qbittorrent
        property: password
    - secretKey: plex_token
      remoteRef:
        key: plex
        property: token
