# yaml-language-server: $schema=https://json.schemastore.org/kustomization
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./rbac.yaml
  - ./external-secret.yaml
  - ./tofu-state-obc.yaml
  - ./tofu-state-backup-cronjob.yaml
  - ./download-client-config.yaml
  - ./app-logins.yaml
  - ./cleanuparr-config.yaml
  - ./terraform-prowlarr.yaml
  - ./terraform-sonarr.yaml
  - ./terraform-radarr.yaml
configMapGenerator:
  - name: app-logins
    files:
      - app-logins.py=./config/app-logins.py
  - name: cleanuparr-config
    files:
      - cleanuparr-config.py=./config/cleanuparr-config.py
generatorOptions:
  disableNameSuffixHash: true
