---
apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: devopsarr-prowlarr
spec:
  path: ./kubernetes/terraform/prowlarr
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 30m
  retryInterval: 5m
  approvePlan: auto
  storeReadablePlan: human
  varsFrom:
    - kind: Secret
      name: devopsarr-secrets
  destroyResourcesOnDeletion: true
