# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: external-secrets
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    priorityClassName: infrastructure-critical
    installCRDs: true
    serviceMonitor:
      enabled: true
    grafanaDashboard:
      enabled: true
    leaderElect: true
    replicaCount: 2
    podDisruptionBudget:
      enabled: true
      minAvailable: 1
    webhook:
      replicaCount: 2
      podDisruptionBudget:
        enabled: true
        minAvailable: 1
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        memory: 128Mi
    tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
