# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/volsync.backube/replicationsource_v1alpha1.json
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: image-registry-backup
spec:
  sourcePVC: image-registry-storage
  trigger:
    schedule: "0 4 * * *"
  restic:
    repository: volsync-restic-image-registry
    volumeSnapshotClassName: csi-ceph-filesystem
    cacheCapacity: 2Gi
