# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/configmap.json
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-workload-monitoring-config
data:
  config.yaml: |-
    prometheus:
      retention: 7d
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          memory: 512Mi
      volumeClaimTemplate:
        spec:
          storageClassName: ceph-block
          resources:
            requests:
              storage: 10Gi
