# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: radarr
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: radarr-secret
    template:
      data:
        RADARR__AUTH__APIKEY: "{{ .api_key }}"
        RADARR__AUTH__USERNAME: "{{ .username }}"
        RADARR__AUTH__PASSWORD: "{{ .password }}"
  dataFrom:
    - extract:
        key: radarr
