# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: radarr
spec:
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: radarr
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    controllers:
      radarr:
        annotations:
          reloader.stakater.com/auto: "true"
        serviceAccount:
          name: radarr
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/radarr
              tag: 6.2.1.10461
            env:
              RADARR__AUTH__METHOD: Forms
              RADARR__AUTH__REQUIRED: Enabled
              RADARR__SERVER__PORT: "7878"
              TZ: Asia/Dubai
            envFrom:
              - secretRef:
                  name: radarr-secret
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: 7878
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 3
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: 7878
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 3
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: 7878
                  periodSeconds: 10
                  failureThreshold: 30
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop: ["ALL"]
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                cpu: 500m
                memory: 4Gi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seLinuxOptions:
          level: "s0"
    service:
      app:
        controller: radarr
        ports:
          http:
            port: 7878
    persistence:
      config:
        existingClaim: radarr-config
      downloads:
        existingClaim: downloads
        globalMounts:
          - path: /downloads
      media:
        existingClaim: media
        globalMounts:
          - path: /media
      tmp:
        type: emptyDir
