# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/persistentvolume.json
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: radarr-media
  labels:
    app.kubernetes.io/name: radarr
spec:
  capacity:
    storage: 10Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - nfsvers=4.1
    - hard
    - timeo=300
    - retrans=2
  nfs:
    server: nas.grappleberry.xyz
    path: /volume1/media
  claimRef:
    namespace: default
    name: radarr-media
