# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/volsync.backube/replicationsource_v1alpha1.json
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: radarr-config-backup
spec:
  sourcePVC: radarr-config
  trigger:
    schedule: "0 3 * * *"
  restic:
    repository: volsync-restic-radarr
    volumeSnapshotClassName: csi-ceph-blockpool
    cacheCapacity: 1Gi
