# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: buildarr-secrets
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: buildarr-secrets
    template:
      data:
        # *Arr API Keys
        SONARR_API_KEY: "{{ .sonarr_api_key }}"
        RADARR_API_KEY: "{{ .radarr_api_key }}"
        PROWLARR_API_KEY: "{{ .prowlarr_api_key }}"
        # Download Client API Keys
        SABNZBD_API_KEY: "{{ .sabnzbd_api_key }}"
        QBITTORRENT_USERNAME: "{{ .qbittorrent_username }}"
        QBITTORRENT_PASSWORD: "{{ .qbittorrent_password }}"
        # Plex
        PLEX_TOKEN: "{{ .plex_token }}"
        # Indexers
        NZBGEEK_API_KEY: "{{ .nzbgeek_api_key }}"
        # App Frontend Credentials (for Buildarr to authenticate)
        PROWLARR_USERNAME: "{{ .prowlarr_username }}"
        PROWLARR_PASSWORD: "{{ .prowlarr_password }}"
        SONARR_USERNAME: "{{ .sonarr_username }}"
        SONARR_PASSWORD: "{{ .sonarr_password }}"
        RADARR_USERNAME: "{{ .radarr_username }}"
        RADARR_PASSWORD: "{{ .radarr_password }}"
  data:
    # Sonarr
    - secretKey: sonarr_api_key
      remoteRef:
        key: sonarr
        property: api_key
    - secretKey: sonarr_username
      remoteRef:
        key: sonarr
        property: username
    - secretKey: sonarr_password
      remoteRef:
        key: sonarr
        property: password
    # Radarr
    - secretKey: radarr_api_key
      remoteRef:
        key: radarr
        property: api_key
    - secretKey: radarr_username
      remoteRef:
        key: radarr
        property: username
    - secretKey: radarr_password
      remoteRef:
        key: radarr
        property: password
    # Prowlarr
    - secretKey: prowlarr_api_key
      remoteRef:
        key: prowlarr
        property: api_key
    - secretKey: prowlarr_username
      remoteRef:
        key: prowlarr
        property: username
    - secretKey: prowlarr_password
      remoteRef:
        key: prowlarr
        property: password
    # SABnzbd
    - secretKey: sabnzbd_api_key
      remoteRef:
        key: sabnzbd
        property: api_key
    # qBittorrent
    - secretKey: qbittorrent_username
      remoteRef:
        key: qbittorrent
        property: username
    - secretKey: qbittorrent_password
      remoteRef:
        key: qbittorrent
        property: password
    # Plex
    - secretKey: plex_token
      remoteRef:
        key: plex
        property: token
    # Indexers
    - secretKey: nzbgeek_api_key
      remoteRef:
        key: nzbgeek
        property: api_key
