# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: certificates-export-config
  namespace: flux-system
spec:
  targetNamespace: network
  path: ./kubernetes/infrastructure/configs/certificates-export-config/app
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: certificates-import-config
      namespace: flux-system
    - name: cluster-issuers-config
      namespace: flux-system
  interval: 10m
  timeout: 5m
  retryInterval: 1m
  prune: true
  wait: false
