# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plex
spec:
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: plex
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    controllers:
      plex:
        annotations:
          reloader.stakater.com/auto: "true"
        serviceAccount:
          name: plex
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/plex
              tag: 1.43.0.10492
            env:
              TZ: Asia/Dubai
              PLEX_ADVERTISE_URL: http://192.168.227.206:32400
              PLEX_NO_AUTH_NETWORKS: 192.168.227.0/24,10.128.0.0/14
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /identity
                    port: 32400
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /identity
                    port: 32400
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop: ["ALL"]
            resources:
              requests:
                cpu: 100m
                memory: 512Mi
              limits:
                cpu: 4000m
                memory: 8Gi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seLinuxOptions:
          level: "s0"
    service:
      app:
        controller: plex
        type: LoadBalancer
        externalTrafficPolicy: Local
        annotations:
          tailscale.com/expose: "true"
          metallb.universe.tf/loadBalancerIPs: 192.168.227.206
        ports:
          http:
            port: 32400
    persistence:
      config:
        existingClaim: plex-config
      media:
        existingClaim: media
        globalMounts:
          - path: /media
            readOnly: true
      tmp:
        type: emptyDir
      transcode:
        type: emptyDir
