# yaml-language-server: $schema=https://json.schemastore.org/kustomization
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./kube-system
  - ./rook-ceph
  - ./observability
  - ./default
  - ./etcd-backup
  - ./openshift-apiserver
  - ./openshift-machineconfig
  - ./openshift-monitoring
  - ./openshift-image-registry
