# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/configmap.json
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: recyclarr-config
data:
  recyclarr.yml: |-
    # yaml-language-server: $schema=https://raw.githubusercontent.com/recyclarr/recyclarr/master/schemas/config-schema.json

    sonarr:
      sonarr:
        base_url: http://sonarr.default.svc.cluster.local:8989
        api_key: !env_var SONARR_API_KEY
        delete_old_custom_formats: true
        replace_existing_custom_formats: true
        include:
          - template: sonarr-quality-definition-series
          - template: sonarr-v4-quality-profile-web-2160p
          - template: sonarr-v4-custom-formats-web-2160p
          - template: sonarr-v4-quality-profile-web-1080p
          - template: sonarr-v4-custom-formats-web-1080p
        quality_profiles:
          - name: WEB-2160p
          - name: WEB-1080p

    radarr:
      radarr:
        base_url: http://radarr.default.svc.cluster.local:7878
        api_key: !env_var RADARR_API_KEY
        delete_old_custom_formats: true
        replace_existing_custom_formats: true
        include:
          - template: radarr-quality-definition-movie
          - template: radarr-quality-profile-uhd-bluray-web
          - template: radarr-custom-formats-uhd-bluray-web
          - template: radarr-quality-profile-hd-bluray-web
          - template: radarr-custom-formats-hd-bluray-web
        quality_profiles:
          - name: UHD Bluray + WEB
          - name: HD Bluray + WEB
