# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: recyclarr-secrets
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: recyclarr-secrets
    template:
      data:
        SONARR_API_KEY: "{{ .sonarr_api_key }}"
        RADARR_API_KEY: "{{ .radarr_api_key }}"
  data:
    - secretKey: sonarr_api_key
      remoteRef:
        key: sonarr
        property: api_key
    - secretKey: radarr_api_key
      remoteRef:
        key: radarr
        property: api_key
