# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: volsync-restic-plex
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: volsync-restic-plex
    template:
      data:
        RESTIC_REPOSITORY: /mnt/restic-repo/plex
        RESTIC_PASSWORD: "{{ .RESTIC_PASSWORD }}"
  dataFrom:
    - extract:
        key: volsync
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: volsync-restic-sabnzbd
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: volsync-restic-sabnzbd
    template:
      data:
        RESTIC_REPOSITORY: /mnt/restic-repo/sabnzbd
        RESTIC_PASSWORD: "{{ .RESTIC_PASSWORD }}"
  dataFrom:
    - extract:
        key: volsync
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: volsync-restic-qbittorrent
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: volsync-restic-qbittorrent
    template:
      data:
        RESTIC_REPOSITORY: /mnt/restic-repo/qbittorrent
        RESTIC_PASSWORD: "{{ .RESTIC_PASSWORD }}"
  dataFrom:
    - extract:
        key: volsync
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: volsync-restic-overseerr
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: volsync-restic-overseerr
    template:
      data:
        RESTIC_REPOSITORY: /mnt/restic-repo/overseerr
        RESTIC_PASSWORD: "{{ .RESTIC_PASSWORD }}"
  dataFrom:
    - extract:
        key: volsync
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: volsync-restic-sonarr
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: volsync-restic-sonarr
    template:
      data:
        RESTIC_REPOSITORY: /mnt/restic-repo/sonarr
        RESTIC_PASSWORD: "{{ .RESTIC_PASSWORD }}"
  dataFrom:
    - extract:
        key: volsync
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: volsync-restic-radarr
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: volsync-restic-radarr
    template:
      data:
        RESTIC_REPOSITORY: /mnt/restic-repo/radarr
        RESTIC_PASSWORD: "{{ .RESTIC_PASSWORD }}"
  dataFrom:
    - extract:
        key: volsync
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: volsync-restic-prowlarr
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: volsync-restic-prowlarr
    template:
      data:
        RESTIC_REPOSITORY: /mnt/restic-repo/prowlarr
        RESTIC_PASSWORD: "{{ .RESTIC_PASSWORD }}"
  dataFrom:
    - extract:
        key: volsync
