# yaml-language-server: $schema=https://json.schemastore.org/kustomization
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./oci-repository.yaml
  - ./external-secret.yaml
  - ./pvc.yaml
  - ./rbac.yaml
  - ./helm-release.yaml
  - ./route.yaml
  - ./volsync.yaml
  - ./config-cronjob.yaml
configMapGenerator:
  - name: tdarr-config
    files:
      - sync.js=./config/sync.js
generatorOptions:
  disableNameSuffixHash: true
components:
  - ../../../../components/volsync-restic-defaults
