---
name: ci
on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop, main]
permissions:
  contents: read
jobs:
  lint-yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
        with:
          go-version: stable
      - run: go install github.com/google/yamlfmt/cmd/yamlfmt@latest
      - run: yamlfmt -lint .
  validate-flux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: fluxcd/flux2/action@main
      - run: pip install flux-local
      - run: flux-local test --path kubernetes/clusters/production --enable-helm --all-namespaces
